(** SMT constraint trees.

    Represents the constraints generated by refined typechecking.
    Follows the syntax tree conventions: shape functor, abstract knot-tied type,
    info parameter carrying source positions. *)

(** {1 Shape functor} *)

type ('a, 'e) ctF =
  | Top
  | Bot
  | And of 'a * 'a
  | Forall of Var.t * Sort.sort * 'a
  | Impl of 'e * 'a
  | Atom of 'e
  | Is of Label.t * 'e

val map_shape : ('a -> 'b) -> ('a, 'e) ctF -> ('b, 'e) ctF

(** {1 Abstract knot-tied type} *)

type ('e, 'b) t

val mk : 'b -> (('e, 'b) t, 'e) ctF -> ('e, 'b) t
val info : ('e, 'b) t -> 'b
val shape : ('e, 'b) t -> (('e, 'b) t, 'e) ctF
val map : ('b -> 'c) -> ('e, 'b) t -> ('e, 'c) t

(** {1 Concrete types} *)

type ct = (CoreExpr.ce, < loc : SourcePos.t >) t
type typed_ct = (CoreExpr.typed_ce, < loc : SourcePos.t >) t

(** {1 Smart constructors}

    Each takes a [SourcePos.t] and simplifies trivial cases ([Top ∧ C = C]). *)

val top : SourcePos.t -> ('e, < loc : SourcePos.t >) t
val bot : SourcePos.t -> ('e, < loc : SourcePos.t >) t
val conj : SourcePos.t -> ('e, < loc : SourcePos.t >) t -> ('e, < loc : SourcePos.t >) t -> ('e, < loc : SourcePos.t >) t
val impl : SourcePos.t -> 'e -> ('e, < loc : SourcePos.t >) t -> ('e, < loc : SourcePos.t >) t
val forall_ : SourcePos.t -> Var.t -> Sort.sort -> ('e, < loc : SourcePos.t >) t -> ('e, < loc : SourcePos.t >) t
val atom : SourcePos.t -> 'e -> ('e, < loc : SourcePos.t >) t
val is_ : SourcePos.t -> Label.t -> 'e -> ('e, < loc : SourcePos.t >) t

(** {1 Printing} *)

val print_gen : (Format.formatter -> Var.t -> unit) -> Format.formatter -> (_ CoreExpr.t, _) t -> unit
val print : Format.formatter -> (_ CoreExpr.t, _) t -> unit
val to_string : (_ CoreExpr.t, _) t -> string

module Test : sig
  val test : QCheck.Test.t list
end
