(** SMT constraint trees.

    Represents the constraints generated by refined typechecking.
    Follows the syntax tree conventions: shape functor, abstract knot-tied type,
    info parameter carrying source positions. *)

(** {1 Shape functor} *)

type ('a, 'e) ctF =
  | Top
  | Bot
  | And of 'a * 'a
  | Forall of Var.t * Sort.sort * 'a
  | Impl of 'e * 'a
  | Atom of 'e
  | Is of Label.t * 'e

val map_shape : ('a -> 'b) -> ('a, 'e) ctF -> ('b, 'e) ctF

(** {1 Abstract knot-tied type} *)

type ('e, 'b) t

val mk : 'b -> (('e, 'b) t, 'e) ctF -> ('e, 'b) t
val info : ('e, 'b) t -> 'b
val shape : ('e, 'b) t -> (('e, 'b) t, 'e) ctF
val map : ('b -> 'c) -> ('e, 'b) t -> ('e, 'c) t

(** {1 Concrete types} *)

type ct = (CoreExpr.ce, SourcePos.info) t
type typed_ct = (CoreExpr.typed_ce, SourcePos.info) t

(** {1 Smart constructors}

    Each takes a [SourcePos.t] and simplifies trivial cases ([Top ∧ C = C]). *)

val top : SourcePos.t -> ('e, SourcePos.info) t
val bot : SourcePos.t -> ('e, SourcePos.info) t
val conj : SourcePos.t -> ('e, SourcePos.info) t -> ('e, SourcePos.info) t -> ('e, SourcePos.info) t
val impl : SourcePos.t -> 'e -> ('e, SourcePos.info) t -> ('e, SourcePos.info) t
val forall_ : SourcePos.t -> Var.t -> Sort.sort -> ('e, SourcePos.info) t -> ('e, SourcePos.info) t
val atom : SourcePos.t -> 'e -> ('e, SourcePos.info) t
val is_ : SourcePos.t -> Label.t -> 'e -> ('e, SourcePos.info) t

(** {1 Error-propagating smart constructors}

    Same shape as the unprimed forms but accept errkind inputs.  When
    a key payload is [Error _], the constructor folds to a constraint
    that contributes nothing — typically [Top] for [Atom]/[Is] and
    "drop the binder/antecedent" for [Forall]/[Impl] — so error
    propagation never invents a spurious obligation.  Polymorphic in
    the [Result]'s error type. *)

val atom' :
  SourcePos.t -> ('e_ce, _) result -> ('e_ce, SourcePos.info) t
(** [atom' pos ce_r] is [atom pos ce] when [ce_r = Ok ce], else [top pos]. *)

val is_' :
  SourcePos.t -> Label.t -> ('e_ce, _) result ->
  ('e_ce, SourcePos.info) t
(** [is_' pos l ce_r] is [is_ pos l ce] when [ce_r = Ok ce], else [top pos]. *)

val impl' :
  SourcePos.t -> ('e_ce, _) result ->
  ('e_ce, SourcePos.info) t -> ('e_ce, SourcePos.info) t
(** [impl' pos ce_r body] is [impl pos ce body] when [ce_r = Ok ce],
    else [body] — a missing antecedent collapses to its consequent. *)

val forall_' :
  SourcePos.t -> (Var.t, _) result -> (Sort.sort, _) result ->
  ('e, SourcePos.info) t -> ('e, SourcePos.info) t
(** [forall_' pos x_r tau_r body] is [forall_ pos x tau body] when both
    [x_r] and [tau_r] are [Ok]; else [body] — a missing binder or sort
    collapses to its body. *)

(** {1 Printing} *)

val print_gen : (Format.formatter -> Var.t -> unit) -> Format.formatter -> (_ CoreExpr.t, _) t -> unit
val print : Format.formatter -> (_ CoreExpr.t, _) t -> unit
val to_string : (_ CoreExpr.t, _) t -> string

module Test : sig
  val test : QCheck.Test.t list
end
