(** Refined typechecker.

    Implements all refined typing judgements from the Ott specification.
    Elaboration delegates to [Elaborate.synth] / [Elaborate.check] via
    [RSig.comp] and [RCtx.erase].  Uses [typed_ce] throughout to
    preserve sort/ctx/eff info from elaboration.

    Every typing judgement consumes / produces its [ce]/[sort]/[pf]
    carriers as [(_, Error.kind) result].  Inputs that are [Error _]
    flow through to placeholders without aborting; outputs that are
    [Error _] mean "this position couldn't be synthesized" and the
    caller's typed AST records the same error on its rinfo's [#answer]
    field.  No typing rule pattern-matches a [Result] in its body —
    the result-handling lives in helper wrappers (view extractors,
    primed [Subst]/[Constraint] constructors, [extend_*_opt],
    [pf_eq_e], etc.). *)

(** {1 Top-level entry points} *)

val check_rprog :
  RProg.parsed ->
  (RProg.typed * RSig.t * Constraint.typed_ct) ElabM.t
(** [check_rprog prog] typechecks a refined program, returning the
    fully annotated program, final signature, and typed constraint
    tree.  Every refined-expression node in the output carries
    [CoreExpr.typed_info] (context, sort, effect). *)

val check_rdecl :
  RSig.t -> Constraint.typed_ct ->
  (SurfExpr.se, < loc : SourcePos.t >, Var.t) RProg.decl ->
  ((CoreExpr.typed_ce, RProg.typed_rinfo, Var.t) RProg.decl
   * RSig.t * Constraint.typed_ct) ElabM.t
(** [check_rdecl rsig ct d] typechecks a single refined declaration
    against [rsig], conjoining any new constraints with [ct].
    Returns the typed declaration, updated signature, and constraint
    tree. *)

val collect_errors_rprog : RProg.typed -> Error.t list
(** [collect_errors_rprog prog] returns every error recorded on
    [info#answer] anywhere in the typed refined program — across
    typed_rinfo nodes (RPat, ProofSort, RefinedExpr.{lpf,rpf,crt,
    spine}) and embedded typed_ce sub-trees.  Pre-order over decls
    then main; within each tree, source order. *)

(** {1 Typed-AST aliases used by the judgement signatures} *)

type checked_lpf =
  (CoreExpr.typed_ce, RProg.typed_rinfo, Var.t) RefinedExpr.lpf
type checked_rpf =
  (CoreExpr.typed_ce, RProg.typed_rinfo, Var.t) RefinedExpr.rpf
type checked_crt =
  (CoreExpr.typed_ce, RProg.typed_rinfo, Var.t) RefinedExpr.crt
type checked_spine =
  (CoreExpr.typed_ce, RProg.typed_rinfo, Var.t) RefinedExpr.spine

(** {1 Typing judgements: logical proof facts} *)

val synth_lpf :
  RSig.t -> RCtx.t ->
  RefinedExpr.parsed_lpf ->
  (checked_lpf
   * (CoreExpr.typed_ce, Error.kind) result
   * RCtx.t
   * Constraint.typed_ct) ElabM.t
(** [synth_lpf rs delta lpf] synthesises an lpf, returning the typed
    lpf, the synthesised proposition (errkind: [Error _] when the lpf
    can't be synthesised, e.g. a bare [auto] or hole), the (possibly
    affinised) output context, and the constraint generated by the
    rule.

    Spec: [RS; Δ ⊢ lpf ⇒ φ ⊣ Δ' ↝ Ct]. *)

val check_lpf :
  RSig.t -> RCtx.t ->
  RefinedExpr.parsed_lpf ->
  (CoreExpr.typed_ce, Error.kind) result ->
  (checked_lpf * RCtx.t * Constraint.typed_ct) ElabM.t
(** [check_lpf rs delta lpf ce] checks that [lpf] proves [ce].  When
    [ce] is [Error _] (e.g. propagated from an upstream view extract
    that misshaped its predicate), the resulting typed lpf records
    the error and the constraint collapses to [Top].

    Spec: [RS; Δ ⊢ lpf ⇐ ce ⊣ Δ' ↝ Ct]. *)

val lpat_match :
  RSig.t -> RCtx.t ->
  (< loc : SourcePos.t >, Var.t) RPat.lpat ->
  (CoreExpr.typed_ce, Error.kind) result ->
  ((RProg.typed_rinfo, Var.t) RPat.lpat * RCtx.t * Constraint.typed_ct)
    ElabM.t
(** [lpat_match rs delta lp prop] matches a logical pattern [lp]
    against an errkind proposition [prop], extending [delta] with the
    pattern's binders and emitting [Constraint.atom prop] when [lp]
    is [LAuto].  When [prop] is [Error _], binders are added as
    [extend_unknown]. *)

(** {1 Typing judgements: resource proof facts} *)

val synth_rpf :
  RSig.t -> RCtx.t ->
  RefinedExpr.parsed_rpf ->
  (checked_rpf
   * (CoreExpr.typed_ce, Error.kind) result   (* synthesised pred *)
   * (CoreExpr.typed_ce, Error.kind) result   (* synthesised value *)
   * RCtx.t
   * Constraint.typed_ct) ElabM.t
(** [synth_rpf rs delta rpf] synthesises an rpf, returning the typed
    rpf together with the (errkind) synthesised predicate and value.
    Synth-only rule: only [RVar] and [RAnnot] (and [RHole] for
    bookkeeping) succeed; any other rpf shape ascribes via [: pred @
    value] and the synthesised pair is [Error K_cannot_synthesize].

    Spec: [RS; Δ ⊢ rpf ⇒ ce @ ce' ⊣ Δ' ↝ Ct]. *)

val check_rpf :
  RSig.t -> RCtx.t ->
  RefinedExpr.parsed_rpf ->
  (CoreExpr.typed_ce, Error.kind) result ->   (* expected pred *)
  (CoreExpr.typed_ce, Error.kind) result ->   (* expected value *)
  (checked_rpf * RCtx.t * Constraint.typed_ct) ElabM.t
(** [check_rpf rs delta rpf ce_pred ce_value] checks that [rpf]
    inhabits the resource type [ce_pred @ ce_value].  Errkind inputs
    flow through view extraction, lookup, substitution, and the
    recursive sub-checks; on [Error] inputs the rule emits a
    placeholder body but still recurses so the LSP keeps a typed
    AST.

    Spec: [RS; Δ ⊢ rpf ⇐ ce @ ce' ⊣ Δ' ↝ Ct]. *)

val rpat_match :
  RSig.t -> RCtx.t -> Effect.t ->
  (< loc : SourcePos.t >, Var.t) RPat.rpat ->
  (CoreExpr.typed_ce, Error.kind) result ->   (* pred *)
  (CoreExpr.typed_ce, Error.kind) result ->   (* value *)
  ((RProg.typed_rinfo, Var.t) RPat.rpat * RCtx.t * Constraint.typed_ct)
    ElabM.t
(** [rpat_match rs delta eff rp pred value] matches a resource
    pattern [rp] against the resource type [pred @ value].  When
    either input is [Error _], every binder in [rp] is added to
    [delta] via [extend_unknown] (preserving variable scope for
    downstream use). *)

(** {1 Typing judgements: refined terms} *)

val synth_crt :
  RSig.t -> RCtx.t -> Effect.t ->
  RefinedExpr.parsed_crt ->
  (checked_crt
   * ((CoreExpr.typed_ce, RProg.typed_rinfo, Var.t) ProofSort.t,
      Error.kind) result
   * RCtx.t
   * Constraint.typed_ct) ElabM.t
(** [synth_crt rs delta eff crt] synthesises the proof sort [Pf] for
    [crt].  Returns the typed crt, the (errkind) synthesised proof
    sort, the output context, and the rule's constraint.  The pf is
    [Error _] for unsynthesisable crts (e.g. [exfalso], [hole]).

    Spec: [RS; Δ ⊢_eff crt ⇒ Pf ⊣ Δ' ↝ Ct]. *)

val check_crt :
  RSig.t -> RCtx.t -> Effect.t ->
  RefinedExpr.parsed_crt ->
  ((CoreExpr.typed_ce, RProg.typed_rinfo, Var.t) ProofSort.t,
   Error.kind) result ->                       (* expected pf *)
  (checked_crt * RCtx.t * Constraint.typed_ct) ElabM.t
(** [check_crt rs delta eff crt pf] checks that [crt] inhabits the
    proof sort [pf].  When [pf] is [Error _], the rule's [#answer]
    records the error and [pf_eq] (in synth-and-check fallthrough)
    short-circuits to [Top].

    Spec: [RS; Δ ⊢_eff crt ⇐ Pf ⊣ Δ' ↝ Ct]. *)

val q_match :
  RSig.t -> RCtx.t -> Effect.t ->
  (< loc : SourcePos.t >, Var.t) RPat.t ->
  ((CoreExpr.typed_ce, RProg.typed_rinfo, Var.t) ProofSort.t,
   Error.kind) result ->
  ((RProg.typed_rinfo, Var.t) RPat.t * RCtx.t * Constraint.typed_ct)
    ElabM.t
(** [q_match rs delta eff pat pf] matches the refined-term pattern
    [pat] against the proof sort [pf], walking [pat]'s entries
    ([QCore], [QLog], [QRes], [QDepRes], [QNil]) in lockstep with the
    pf entries via the [view_get_pf_*] family.  Errkind input is
    converted to [pf option] at the boundary; [None] (= [Error _]) is
    handled uniformly by the views as "no expected entry available".

    Used by [check_crt CLet] / [CLetLog] / [CLetRes] / [CLetCore] and
    by [check_one_rdecl] to pattern-match against an rfun's
    domain. *)

(** {1 Typing judgement: spines (refined-call argument lists)} *)

val check_spine :
  RSig.t -> RCtx.t -> Effect.t ->
  RefinedExpr.parsed_spine ->
  ((CoreExpr.typed_ce, RProg.typed_rinfo, Var.t) ProofSort.t,
   Error.kind) result ->
  ((CoreExpr.typed_ce, RProg.typed_rinfo, Var.t) ProofSort.t,
   Error.kind) result ->
  (checked_spine
   * ((CoreExpr.typed_ce, RProg.typed_rinfo, Var.t) ProofSort.t,
      Error.kind) result
   * RCtx.t
   * Constraint.typed_ct) ElabM.t
(** [check_spine rs delta eff spine domain codomain] checks [spine]
    against an rfun's [domain] and [codomain] (each errkind),
    walking [spine] entries ([SCore]/[SLog]/[SRes]/[SNil]) in
    lockstep with [domain] via the entry-tag comparison and
    substituting [codomain] as binders are matched.  Returns the
    typed spine, the (instantiated) codomain, the output context,
    and the rule's constraint.

    Spec: [RS; Δ ⊢_eff rsp : Pf₁ ⊸ Pf₂ ⊃ Pf ⊣ Δ' ↝ Ct].

    Both inputs are errkind so callers can pass the components of
    [lookup_rf_m]'s triple straight through; an [Error] domain is
    treated as "no entries to match", and an [Error] codomain
    returns an [Error] codomain unchanged. *)

(** {1 Helper judgement: core patterns} *)

val cpat_match :
  RSig.t -> RCtx.t ->
  (Effect.t, Error.kind) result ->
  (< loc : SourcePos.t >, Var.t) RPat.cpat ->
  (Sort.sort, Error.kind) result ->
  ((RProg.typed_rinfo, Var.t) RPat.cpat * RCtx.t * CoreExpr.typed_ce)
    ElabM.t
(** [cpat_match rs delta eff cp sort] matches a core pattern [cp]
    against the (errkind) sort, extending [delta] and returning the
    cpat's witness expression.  Used by [rpat_match RTake]/[RLet] and
    [q_match QCore].  Errkind sort: [Error _] adds binders as
    [extend_unknown]. *)

(** {1 Test interface} *)

module Test : sig
  val test : QCheck.Test.t list
  val pf_eq :
    SourcePos.t -> RSig.t -> RCtx.t ->
    (CoreExpr.typed_ce, RProg.typed_rinfo, Var.t) ProofSort.t ->
    (CoreExpr.typed_ce, RProg.typed_rinfo, Var.t) ProofSort.t ->
    (Constraint.typed_ct * Error.t list) ElabM.t
  val with_delta_check : (unit -> 'a) -> 'a
  (** [with_delta_check f] runs [f] with the Δ ⊓ Δ' = Δ' monotonicity
      assertion enabled in [check_crt] / [synth_crt]. *)
end
